# Generated by Django 5.2.4 on 2026-08-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_banner_title', models.CharField(default='UP TO 35% OFF', max_length=255)),
                ('promo_banner_subtitle', models.CharField(default='ON FIRST ORDER', max_length=255)),
                ('promo_banner_button_text', models.CharField(default='Download Now', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
