# Generated by Django 5.2.4 on 2026-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
