# Generated by Django 5.2.4 on 2026-08-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sitesettings_promo_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_favicon',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
