# Generated by Django 5.2.4 on 2026-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sitesettings_site_favicon_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_banner_link',
            field=models.CharField(default='/products', max_length=255),
        ),
    ]
