# Generated by Django 5.2.4 on 2026-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_sitesettings_promo_banner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enable_2fa',
            field=models.BooleanField(default=True),
        ),
    ]
