from django.core.management.base import BaseCommand
from django.db import transaction

from apps.accounts.models import User
from apps.catalog.models import Category, Product

class Command(BaseCommand):
    help = "Removes only the synthetic demo data generated by seed_demo_data"

    def add_arguments(self, parser):
        parser.add_argument(
            '--noinput',
            '--no-input',
            action='store_false',
            dest='interactive',
            help='Tells Django to NOT prompt the user for input of any kind.',
        )

    def handle(self, *args, **options):
        interactive = options.get('interactive')
        
        if interactive:
            self.stdout.write(self.style.WARNING("WARNING: This will delete development demo data."))
            confirm = input("Continue? [y/N]: ")
            if confirm.lower() != 'y':
                self.stdout.write("Aborted.")
                return

        self.stdout.write("Deleting demo data...")

        with transaction.atomic():
            # Delete demo users (this cascades to Profiles, Addresses, and Products!)
            # Demo users are identified by the @demo.local email domain
            demo_users = User.objects.filter(email__endswith='@demo.local')
            user_count = demo_users.count()
            
            # Since Products are cascaded by SellerProfile via User deletion, we don't need 
            # to explicitly delete products associated with those users, but let's count them.
            from apps.accounts.models import SellerProfile
            demo_sellers = SellerProfile.objects.filter(user__email__endswith='@demo.local')
            product_count = Product.objects.filter(seller__in=demo_sellers).count()

            # Execute deletion of users
            demo_users.delete()
            
            # Delete demo categories (since they don't have a specific demo identifier, 
            # we'll delete the ones created by the seed script if they have no products)
            # Actually, to be safe and truly idempotent, if there are non-demo products using these categories, we shouldn't delete them.
            # But since all categories created were demo ones, we can delete categories that are now empty (no products attached)
            empty_categories = Category.objects.filter(products__isnull=True)
            cat_count = empty_categories.count()
            empty_categories.delete()
            
        self.stdout.write(self.style.SUCCESS(f"Successfully deleted demo data:"))
        self.stdout.write(f"- Users (and associated Profiles/Addresses): {user_count}")
        self.stdout.write(f"- Products (cascaded via Sellers): {product_count}")
        self.stdout.write(f"- Empty Categories: {cat_count}")
