from enum import Enum


class RoleType(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    SELLER = "SELLER"
    BUYER = "BUYER"


class PermissionType(str, Enum):
    USER_VIEW = "USER_VIEW"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DELETE = "USER_DELETE"
    SELLER_VIEW = "SELLER_VIEW"
    SELLER_APPROVE = "SELLER_APPROVE"
    SELLER_SUSPEND = "SELLER_SUSPEND"
    ADMIN_VIEW = "ADMIN_VIEW"
    ADMIN_CREATE = "ADMIN_CREATE"
    ADMIN_UPDATE = "ADMIN_UPDATE"
    ADMIN_DELETE = "ADMIN_DELETE"
